### ISSUE TITLE
Numbers have not updated for a month

### ISSUE THREAD

**Issue by KuleRucket** [scarnecchia/oryx_data#4]
The figures stopped updating so I guess something on the oryx website changed to break the parser.

**Comment by AlexHukri** [comment]
The scraping code still works (I have a copy and it runs fine) so I think it's something else.

**Comment by scarnecchia** [comment]
The issue is that this is running on a cron job on a machine that failed to restart after a power outage, and I won’t be able to physically access it until April 7th.That said, I’m surprised the parser still works, as I have done minimal maintenance on it.On Apr 4, 2024, at 06:25, AlexHukri ***@***.***> wrote:﻿
The scraping code still works (I have a copy and it runs fine) so I think it's something else.

**Comment by AlexHukri** [comment]
Ah, that makes sense then. Yes, the parser works fine – he’s not changed the structure at all. Mind you, if he did, and added a ‘date recorded’ field that would be a good thing!
